@startjson
#highlight "Name"
{
  "Name": "Data Type",
  "correo": "String",
  "numero": "String"

}
@endjson

http://www.plantuml.com/plantuml/png/SoWkIImgoIhEp-DIpiXCpyW1uX859R_4t5Gbhcek1IZJIa799R4aKI6aiY1LIGSad9nVL9IQ3v88BYdAp4k7YEQLvgOM8OjoSTLoEQJcfO1i0000