@startuml
package "Express.js" #DDDDDD {
    class router
}
package "cors" #DDDDDD {

}
package "nodemailer" #DDDDDD {

}
package "ajv" #DDDDDD {

}


class "index" {
    void startApp()
}
class "servidor" {
    port : Integer
    void startServer()
}

class "rutasService" {
    void crearRouter()
}

class "controllers" {
    void mandarCorreoController()
}




class "mailHelper" {
    void sendMail(numero : String, correo : String)
}

class "middlewares" {
    void mandarCorreoSchema(request,response,next)
}

class "validator" {
    bool validarCorreoToken(body : Json)
}

class "schemas" {
    mandarCorreoSchema
}


Express.js <.. servidor  : "<<use>>"


index::startApp   ..>  servidor::startServer : "<<use>>"

servidor ..> cors : "<<use>>"
servidor::startServer ..> rutasService::crearRouter : "<<use>>"

rutasService::crearRouter ..> controllers : "<<use>>"
rutasService::crearRouter ..> middlewares : "<<use>>"
rutasService ..> router : "<<use>>"


controllers ..> mailHelper : "<<use>>"



mailHelper ..> "nodemailer": "<<use>>"

middlewares ..> validator : "<<use>>"

validator ..> schemas : "<<use>>"
validator ..> ajv : "<<use>>"
@enduml