@startjson
#highlight "Name"
{
  "Name": "Data Type",
  "numero": "String"

}
@endjson

http://www.plantuml.com/plantuml/png/SoWkIImgoIhEp-DIpiXCpyW1uX859R_4t5Gbhcek1IZJIa799R4aKI6aiY1LIGSad5UQcrgK3v88BYdAp4jNukAgvN98pKi1cGK0